name: bci-eeg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - pandas>=1.3.0
  - tqdm
  - pyyaml
  - jupyter
  - ipykernel
  - pip:
      # Core ML/DL libraries
      - torch>=2.3.0
      - torchvision>=0.18.0
      - torchaudio>=2.3.0
      # PyTorch Geometric (will be installed separately with correct wheels)
      # - torch-geometric
      # EEG processing
      - mne>=1.5.0
      - mne-bids>=0.15.0
      - moabb>=1.0.0
      - braindecode>=0.8.0
      # ML utilities
      - scikit-learn>=1.2.0
      - einops>=0.6.0
      - hydra-core>=1.3.0
      - tensorboard>=2.12.0
      # Optional Mamba (may fail on some systems)
      # - mamba-ssm[causal-conv1d]
      # Development
      - pytest>=7.0.0
      - black>=22.0.0
      - flake8>=5.0.0

