# 自监督预训练配置
model:
  dataset_type: 'bnci2a'
  n_channels: 22
  n_samples: 1000
  sfreq: 250.0
  
  # FilterBank配置
  filter_bands: [[4, 8], [8, 14], [14, 30], [30, 45]]
  use_adaptive_filterbank: false
  
  # 图卷积配置
  use_graph_conv: true
  graph_hidden_dims: [64, 128]
  graph_output_dim: 128
  
  # S4分支配置
  use_s4_branch: true
  s4_d_model: 128
  s4_d_state: 64
  s4_n_layers: 2
  
  # Mamba分支配置
  use_mamba_branch: true
  mamba_d_model: 128
  mamba_d_state: 16
  mamba_n_layers: 2
  
  # 融合配置
  fusion_method: 'cross_attention'
  fusion_n_heads: 8
  
  # MoE配置
  use_moe: true
  moe_n_experts: 4
  moe_top_k: 2
  
  # 任务配置
  task_configs:
    default:
      d_output: 4
      top_k: 2
  
  # 通用配置
  dropout: 0.1

ssl:
  # 遮罩配置
  mask_ratio: 0.5
  mask_type: 'time_block'  # 'time_block', 'channel_time', 'random'
  min_mask_length: 10
  max_mask_length: 50
  
  # 训练配置
  learning_rate: 1e-3
  weight_decay: 1e-4
  batch_size: 32
  max_epochs: 100
  warmup_epochs: 10
  
  # 调度器配置
  scheduler_type: 'cosine'
  min_lr_factor: 0.01

